### PR TITLE
Deprecate WMIC in favor of `Get-CimInstance`

### LINKED ISSUE #8328: 'wmic' is not recognized as an internal or external command
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 11 Insider Preview Build 22483.1011
- VS Code Version: 1.62.0-insider
- C/C++ Extension Version: 1.7.1
- A clear and concise description of what the bug is:
> Command failed: `wmic process get Name,ProcessId,CommandLine /FORMAT:list`
   'wmic' is not recognized as an internal or external command, operable program or batch file.

**To Reproduce**
`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```
1. Select `(Windows) Attach` configuration in Debug pane, and press `F5` to start debugging.
2. The error described above popped up.

**Additional context**
WMIC is deprecated in favor of CMI cmdlets in PowerShell as of Windows 10 21H1, and has already been removed from Windows 11 22483. See MicrosoftDocs/win32@9f7ba67.

### PR DESCRIPTION
**Pull request by eternalphane**
Add `CimAttachItemsProvider` to retrieve processes with `Get-CimInstance Win32_Process` if powershell is found in `PATH`.

Fixes #8328.

### CODE REVIEW

File: Extension/src/common.ts [hunk 1]
```diff
@@ -1327,3 +1327,21 @@ export function normalizeArg(arg: string): string {
     }
 }
 
+export function findPowerShell(): string | undefined {
```
Comment (WardenGnaw) [inline Extension/src/common.ts:1333]: nit: Since this is in the `common.ts` file. Can you add a comment or a check to ensure this only runs on Windows?
I know we already have the check in `nativeAttach.ts`, but just in case a future developer wants to use this function. It only supports searching Windows `PATH` environment variable.

File: Extension/src/Debugger/nativeAttach.ts [hunk 2]
```diff
@@ -254,3 +256,71 @@ export class WmicProcessParser {
...
+
+export class CimAttachItemsProvider extends NativeAttachItemsProvider {
+    constructor(private pwsh: string) { super(); }
+
+    // Perf numbers on Win10:
+    // TODO
+
+    protected async getInternalProcessEntries(): Promise<Process[]> {
+        const pwshCommand: string = `${this.pwsh} -NoProfile -Command`;
+        const cimCommand: string = 'Get-CimInstance Win32_Process | Format-List -Property Name,ProcessId,CommandLine';
```
Comment (WardenGnaw) [inline Extension/src/Debugger/nativeAttach.ts]: You could use `Get-CimInstance Win32_Process | Select Name,ProcessId,CommandLine | ConvertTo-JSON` to get JSON output and convert each item in the array into a Process object. 

This will clean up the `ParseProcessFromCim` method.

**Review by WardenGnaw — APPROVED** [review]
LGTM

@eternalphane Thank you for your contribution!
