### PR TITLE
Fix SwitchHeaderSource with RevealIfOpen

### LINKED ISSUE #6749: "workbench.editor.revealIfOpen" option does not work for command "C/C++: Switch Header/Source"
VSCode Version: 1.52.1
C++ extension version: v1.1.3
Commit: ea3859d
Date: 2020-12-16T16:30:02.420Z (2 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

Use the C++ extension
HAve two different editor panels
Open a header on one panel, and the implementation (cc) on the other
Set the above option in the user settings.json to true (workbench.editor.revealIfOpen) (possibly restart?)
Use the command "C/C++: Switch Header/Source"
Expected:

The focus should shift to the other editor panel

Actual:

A new tab will open in the active panel, with the corresponding header / implementation file, duplicating the one already open in the other panel.

Does this issue occur when all extensions are disabled?: Yes/No

Unknown

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fixes https://github.com/microsoft/vscode-cpptools/issues/6749 .

### CODE REVIEW

File: Extension/src/LanguageServer/extension.ts [hunk 1]
```diff
@@ -806,14 +806,9 @@ function onSwitchHeaderSource(): void {
                     vscode.window.showTextDocument(document, editor.viewColumn);
                 }
             });
-            // TODO: Handle non-visibleTextEditor...not sure how yet.
+
             if (!foundEditor) {
-                if (vscode.window.activeTextEditor !== undefined) {
-                    // TODO: Change to show it in a different column?
-                    vscode.window.showTextDocument(document, vscode.window.activeTextEditor.viewColumn);
```
Comment (Colengms) [inline Extension/src/LanguageServer/extension.ts:813]: Wasn't this logic intended to address a previous bug here?
Does this fix also address? :  https://github.com/microsoft/vscode-cpptools/issues/2667

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/extension.ts:813]: Yeah -- it was intended to fix the bug that VS Code fixed via adding the revealIfOpen setting. This method leaves the behavior up to VS and the user setting instead of forcing it to use the activeTextEditor.viewColumn.

Yes, this fixes https://github.com/microsoft/vscode-cpptools/issues/2667, i.e. they're duplicate issues. I couldn't locate that.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/extension.ts:813]: It looks like VS Code added revealIfOpen as a mitigation for https://github.com/microsoft/vscode/issues/15178, which is the request to add a more powerful "open editors" API.

**Review by Colengms — APPROVED** [review]
