### PR TITLE
Fix incorrect compiler path with spaces and args squiggle.

### LINKED ISSUE #5215: Compiler path with spaces produces error
Related topic https://community.platformio.org/t/platform-io-compiler-error/12684

1) We provide a full path to the compiler using `compilerPath` option
2) This a path option, so we do not do any modifications because arguments are passed to `compilerArgs`

Yes, we can escape `compilerPath` by default but it looks like a bug.

Thanks!

/cc @valeros @sean-mcmanus

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fixes https://github.com/microsoft/vscode-cpptools/issues/5215

### CODE REVIEW

File: Extension/src/LanguageServer/configurations.ts [hunk 1]
```diff
@@ -1315,7 +1315,7 @@ export class CppProperties {
                         continue;
                     }
                     // Squiggle when the compiler's path has spaces without quotes but args are used.
-                    compilerPathNeedsQuotes = compilerPathAndArgs.additionalArgs
+                    compilerPathNeedsQuotes = (compilerPathAndArgs.additionalArgs && compilerPathAndArgs.additionalArgs.length > 0)
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts:1318]: This same type of error has occurred before. It would be nice if there were a way to track down any other cases.

Comment (michelleangela) [reply Extension/src/LanguageServer/configurations.ts:1318]: Can you also add the "compilerPathAndArgs.additionalArgs.length >0" check after line 1039?

**Review by michelleangela — CHANGES_REQUESTED** [review]

**Comment by sean-mcmanus** [comment]
Yeah, good catch -- without the change the UI shows the error still.

File: Extension/src/LanguageServer/configurations.ts (hunk 1 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:1318]: > Can you also add the "compilerPathAndArgs.additionalArgs.length >0" check after line 1039?

Fixed.

**Review by michelleangela — APPROVED** [review]
