### PR TITLE
Fix the build getting stuck when /link /out: is used to specify the program name

### LINKED ISSUE #10231: debugger will be stuck when use cl.exe options /link /out:
### Environment

- OS and version:  Windows 11 21H2
- VS Code:  1.73.1
- C/C++ extension:  v1.12.4

### Bug Summary and Steps to Reproduce

Bug Summary:
when use the follow configurations, the program will stuck

Steps to reproduce:
1. In this environment...
2. With this config...
3. run a cpp file

### Debugger Configurations

```shell
{
  "tasks": [
    {
      "type": "cppbuild",
      "label": "C/C++ build",
      "command": "cl.exe",
      "args": [
        "/Zi",
        "/EHsc",
        "/nologo",
        "/Iinclude",
        "${file}",
        "/link",
        "/out:${fileDirname}\\output\\main.exe"
      ],
      "options": {
        "cwd": "${fileDirname}"
      },
      "problemMatcher": [
        "$msCompile"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "task"
    }
  ],
  "version": "2.0.0"
} 
```

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(Windows) start",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "${workspaceFolder}/output/main.exe",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${fileDirname}",
      "environment": [],
      "console": "externalTerminal",
      "preLaunchTask": "C/C++ build"
    }

  ]
}
```
```


### Debugger Logs

```shell
workbench.desktop.main.js:sourcemap:87 [Extension Host] rejected promise not handled within 1 second: Error: EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
E @ workbench.desktop.main.js:sourcemap:87
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:1743
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:1743
_invokeHandler @ workbench.desktop.main.js:sourcemap:1743
_receiveRequest @ workbench.desktop.main.js:sourcemap:1743
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:1743
(anonymous) @ workbench.desktop.main.js:sourcemap:1743
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:546
_receiveMessage @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
acceptChunk @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
y @ workbench.desktop.main.js:sourcemap:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:sourcemap:87 [Extension Host] stack trace: Error: EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
	at mkdirSync (node:fs:1336:3)
	at e.mkdirSync (node:electron/js2c/asar_bundle:5:12607)
	at Object.createDirIfNotExistsSync (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:48464:12)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42741:18)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.doBuild (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42737:16)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42731:24)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.open (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42723:16)
	at r.startSendingEvents (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:151912)
	at P._setupExtHostProcessListeners (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:157254)
	at P.attachPtyToTerminal (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:154800)
	at m.$onDidStartTask (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:38662)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
E @ workbench.desktop.main.js:sourcemap:87
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:1743
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:1743
_invokeHandler @ workbench.desktop.main.js:sourcemap:1743
_receiveRequest @ workbench.desktop.main.js:sourcemap:1743
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:1743
(anonymous) @ workbench.desktop.main.js:sourcemap:1743
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:546
_receiveMessage @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
acceptChunk @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
y @ workbench.desktop.main.js:sourcemap:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:sourcemap:2302 [[object Object]]EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2302
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:1743
_invokeHandler @ workbench.desktop.main.js:sourcemap:1743
_receiveRequest @ workbench.desktop.main.js:sourcemap:1743
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:1743
(anonymous) @ workbench.desktop.main.js:sourcemap:1743
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:546
_receiveMessage @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
acceptChunk @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
y @ workbench.desktop.main.js:sourcemap:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:sourcemap:2302 Error: EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
	at mkdirSync (node:fs:1336:3)
	at e.mkdirSync (node:electron/js2c/asar_bundle:5:12607)
	at Object.createDirIfNotExistsSync (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:48464:12)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42741:18)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.doBuild (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42737:16)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42731:24)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.open (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42723:16)
	at r.startSendingEvents (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:151912)
	at P._setupExtHostProcessListeners (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:157254)
	at P.attachPtyToTerminal (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:154800)
	at m.$onDidStartTask (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:38662)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2302
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:1743
_invokeHandler @ workbench.desktop.main.js:sourcemap:1743
_receiveRequest @ workbench.desktop.main.js:sourcemap:1743
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:1743
(anonymous) @ workbench.desktop.main.js:sourcemap:1743
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:546
_receiveMessage @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
invoke @ workbench.desktop.main.js:sourcemap:83
deliver @ workbench.desktop.main.js:sourcemap:83
fire @ workbench.desktop.main.js:sourcemap:83
acceptChunk @ workbench.desktop.main.js:sourcemap:546
(anonymous) @ workbench.desktop.main.js:sourcemap:546
y @ workbench.desktop.main.js:sourcemap:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:sourcemap:609   ERR Line 20: Unexpected token ILLEGAL: Error: Line 20: Unexpected token ILLEGAL
	at ErrorHandler.constructError (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:16835:22)
	at ErrorHandler.createError (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:16851:27)
	at ErrorHandler.throwError (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:16858:21)
	at Scanner.throwUnexpectedToken (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:16987:35)
	at Scanner.scanPunctuator (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:17490:19)
	at Scanner.lex (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:18087:22)
	at Tokenizer.getNextToken (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:18498:84)
	at Object.tokenize (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:11977:36)
	at tokenize (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:4913:34)
	at Object.parse (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:5280:12)
	at ConfigurationSnippetProvider.provideCompletionItems (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:35495:30)
	at K.provideCompletionItems (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:51930)
	at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:77224
	at ne._withAdapter (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:67325)
	at ne.$provideCompletionItems (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:77200)
	at l._doInvokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13680)
	at l._invokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13362)
	at l._receiveRequest (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:12081)
	at l._receiveOneMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:10834)
	at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:8941
	at h.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at g.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at r.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:16515)
	at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:118:17104
	at h.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at g.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at r.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:16515)
	at o._receiveMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:21327)
	at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:18770
	at h.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at g.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at g.acceptChunk (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:13346)
	at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:12476
	at Socket.i (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:24594)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
workbench.desktop.main.js:sourcemap:87 [Extension Host] rejected promise not handled within 1 second: Error: EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
E @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:87 [Extension Host] stack trace: Error: EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
	at mkdirSync (node:fs:1336:3)
	at e.mkdirSync (node:electron/js2c/asar_bundle:5:12607)
	at Object.createDirIfNotExistsSync (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:48464:12)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42741:18)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.doBuild (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42737:16)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42731:24)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.open (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42723:16)
	at r.startSendingEvents (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:151912)
	at P._setupExtHostProcessListeners (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:157254)
	at P.attachPtyToTerminal (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:154800)
	at m.$onDidStartTask (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:38662)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
E @ workbench.desktop.main.js:sourcemap:87
workbench.desktop.main.js:sourcemap:2302 [[object Object]]EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2302
workbench.desktop.main.js:sourcemap:2302 Error: EINVAL: invalid argument, mkdir '/out:C:\Users\zach\Desktop\test\output'
	at mkdirSync (node:fs:1336:3)
	at e.mkdirSync (node:electron/js2c/asar_bundle:5:12607)
	at Object.createDirIfNotExistsSync (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:48464:12)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42741:18)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.doBuild (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42737:16)
	at CustomBuildTaskTerminal.<anonymous> (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42731:24)
	at Generator.next (<anonymous>)
	at c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42428:71
	at new Promise (<anonymous>)
	at __webpack_modules__.7523.__awaiter (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42424:12)
	at CustomBuildTaskTerminal.open (c:\Users\zach\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:42723:16)
	at r.startSendingEvents (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:151912)
	at P._setupExtHostProcessListeners (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:157254)
	at P.attachPtyToTerminal (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:154800)
	at m.$onDidStartTask (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:38662)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2302
```

### Other Extensions

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bobbrow**
Fix: #10231

### CODE REVIEW

File: Extension/src/common.ts [hunk 1]
```diff
@@ -538,7 +541,7 @@ export function createDirIfNotExistsSync(filePath: string | undefined): void {
     }
     const dirPath: string = path.dirname(filePath);
     if (!checkDirectoryExistsSync(dirPath)) {
-        fs.mkdirSync(dirPath);
+        fs.mkdirSync(dirPath, { recursive: true });
```
Comment (sean-mcmanus) [inline Extension/src/common.ts:544]: Is there a bug associated with this change?

**Review by sean-mcmanus — APPROVED** [review]

File: Extension/src/common.ts (hunk 1 above)
Comment (bobbrow) [reply Extension/src/common.ts:544]: No, but you get the same symptoms as #10231 (terminal hang) if you specify a deep path that doesn't exist yet and mkdir fails to create the subfolders.

**Review by Colengms — APPROVED** [review]
