### PR TITLE
Replace use of yauzl with node-stream-zip

### LINKED ISSUE #4381: Buffer() is deprecated due to security and usability issues.
Type: General
Error: Buffer() is deprecated due to security and usability issues.

- OS and Version: Windows X64 10.0.17763
- VS Code Version: 1.38.1
- C/C++ Extension Version:  0.25.1

Stack trace with NODE_OPTIONS=--throw_deprecation

Error: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
	at showFlaggedDeprecation (buffer.js:160:11)
	at new Buffer (buffer.js:175:3)
	at c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46500:18
	at pendGo (c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46747:3)
	at Pend.module.exports.Pend.go (c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46706:5)
	at ReadStream.module.exports.ReadStream._read (c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46498:21)
	at ReadStream.Readable.read (_stream_readable.js:452:10)
	at resume_ (_stream_readable.js:899:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)

### PR DESCRIPTION
**Pull request by Colengms**
Addresses: https://github.com/microsoft/vscode-cpptools/issues/4381

This removes a long-standing deprecation warning (that several users have complained about, over the past few years), caused by a dependency (fd-slicer) of yauzl.

`node-stream-zip` has a much cleaner API and supports async, so the new code is much simpler.

### CODE REVIEW

File: Extension/src/LanguageServer/extension.ts [hunk 1]
```diff
@@ -45,55 +43,28 @@ export const intelliSenseDisabledError: string = "Do not activate the extension
...
-                        // It's OK to close instead of progressing through more files in the zip.
-                        zipfile.close();
-                    });
-                });
-            });
-            zipfile.readEntry();
-        });
+async function initVcpkgDatabase(): Promise<VcpkgDatabase> {
+    const database: VcpkgDatabase = {};
+    const zip = new StreamZip.async({ file: util.getExtensionFilePath('VCPkgHeadersDatabase.zip') });
```
Comment (bobbrow) [inline Extension/src/LanguageServer/extension.ts]: Can any of these new API's fail?  Should we wrap the usage with try/finally?

**Review by sean-mcmanus — APPROVED** [review]
This is for 1.18.0, right? Can you merge main to release before checking this in?

**Review by michelleangela — APPROVED** [review]
