### PR TITLE
resolve Debug configuration

### LINKED ISSUE #8877: refreshing detected tasks after a new compiler is installed
If the user installs a new compiler while VS Code is still open, we might need to refresh the list of detected tasks in `Debugger\configurationProvider.ts`.

### LINKED ISSUE #9106: [Run/Debug Code] button unable to run code from global launch configurations ('program' is missing)
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 11 22000.593
- VS Code Version: 1.65.2
- C/C++ Extension Version: 1.9.7
- Other extensions you installed (and if the issue persists after disabling them): no other related extensions
- A clear and concise description of what the bug is: Can‘t run code through [run/debug] button, but no problem with F5

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Open global (not workspace) settings, add c++ launch configuration
```json
    "launch": {
        "configurations": [
            {
                "name": "C++",
                "type": "cppdbg",
                "request": "launch",
                "program": "${workspaceFolder}/build/${fileBasenameNoExtension}.exe",
                "cwd": "${workspaceFolder}",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ],
                "preLaunchTask": "c++-build", // generate executable program in the build directory
            }
        ]
    }
```
2. Open a c++ source file
3. Click the run/debug button
4. Select the previously added configuration
5. See error: 'program' is missing
image

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

### PR DESCRIPTION
**Pull request by elahehrashedi**
When reading the configs from the User settings, the folder is undefined, similar to SingleFile mode.

User and Workspace configurations are being supported: 
bug fix: https://github.com/microsoft/vscode-cpptools/issues/9106

==========================

when IntelliSenseEngine is Disabled, we need to run the build task separately, and set preLaunchTask to undefined.

bug fix: https://github.com/microsoft/vscode-cpptools/issues/8877

### CODE REVIEW

File: Extension/src/Debugger/configurationProvider.ts [hunk 1]
```diff
@@ -177,6 +180,14 @@ export class DebugConfigurationProvider implements vscode.DebugConfigurationProv
                     return undefined; // Stop debugging
                 }
             }
+            if ((!folder || isIntelliSenseDisabled) && config.preLaunchTask) {
+                /* There are two cases where folder is undefined:
+                 when debugging is done on a single file where there is no folder open,
```
Comment (sean-mcmanus) [inline Extension/src/Debugger/configurationProvider.ts]: Most of our multiline /* */ comment start the new lines with *, e.g.
```
/* one
 * two
 * three
 */

**Review by sean-mcmanus — APPROVED** [review]

File: Extension/src/Debugger/configurationProvider.ts [hunk 2]
```diff
@@ -392,32 +403,27 @@ export class DebugConfigurationProvider implements vscode.DebugConfigurationProv
...
+            config.existing = TaskConfigStatus.configured;
+            return config;
+        });
+        if (existingConfigs) {
+            const areEqual = (config1: vscode.DebugConfiguration, config2: vscode.DebugConfiguration): boolean =>
+                (config1.preLaunchTask === config2.preLaunchTask
+                && config1.type === config2.type && config1.request === config2.request);
+            // Remove the detected configs that are already configured once in launch.json.
+            const dedupExistingConfigs: vscode.DebugConfiguration[] = configs.filter(detectedConfig => !existingConfigs.some(config => {
+                if (areEqual(config, detectedConfig)) {
```
Comment (sean-mcmanus) [inline Extension/src/Debugger/configurationProvider.ts]: Why is areEqual used when it could just directly check config properties? Seems like that just adds more code, unless areEqual was used somewhere else.

File: Extension/src/Debugger/configurationProvider.ts [hunk 3]
```diff
@@ -574,15 +580,28 @@ export class DebugConfigurationProvider implements vscode.DebugConfigurationProv
...
             return undefined;
         }
-        configs = configs.filter(config => (config.name && config.request === "launch" && config.type === type));
+        configs = configs.filter((config: any) => (config.name && config.request === "launch" && config.type === type));
         return configs;
     }
 
+    public async checkDebugConfigExists(configName: string, folder?: vscode.WorkspaceFolder, type?: DebuggerType): Promise<void> {
+        const configs: vscode.DebugConfiguration[] | undefined = await this.getLaunchConfigs(folder, type);
+        if (!configs || configs.length === 0) {
```
Comment (michelleangela) [inline Extension/src/Debugger/configurationProvider.ts]: Code refactor suggestion to remove duplicate Error message:

Instead of checking if `configName` is missing, check if it exists and return when it exists, otherwise it throws an error at the end.

Example with sudo code:
```
const configs = await func();
if ("configs is valid") {
    const selectedConfig = configs.find(...);
    if ("selectedConfig is valid") {
       return; // configName found
    }
}

throw new Error(...);
```

File: Extension/src/Debugger/configurationProvider.ts [hunk 4]
```diff
@@ -627,33 +637,28 @@ export class DebugConfigurationProvider implements vscode.DebugConfigurationProv
...
+        // startDebugging will trigger a call to resolveDebugConfiguration.
+        await vscode.debug.startDebugging(folder, selection.configuration, {noDebug: !debugModeOn});
+
     }
 
-    private async resolvePreLaunchTask(folder: vscode.WorkspaceFolder | undefined, configuration: vscode.DebugConfiguration, debuggerEvent: string, debugModeOn: boolean = true): Promise<void> {
+    private async resolvePreLaunchTask(folder: vscode.WorkspaceFolder | undefined, configuration: vscode.DebugConfiguration, debugModeOn: boolean = true): Promise<void> {
         const debugType: string = debugModeOn ? "debug" : "run";
         const folderMode: string = folder ? "folder" : "singleFile";
+        // if configuration.debuggerEvent === undefined, it means this configuration is elready defined in launch.json and is shown in debugPanel.
```
Comment (michelleangela) [inline Extension/src/Debugger/configurationProvider.ts]: nit: `elready` is misspelled.

**Review by michelleangela — APPROVED** [review]
