### PR TITLE
Fix selection and formatting for CDD (and extra newlines with clang-format)

### LINKED ISSUE #10160: Create declaration/definition does not select the correct range of new inserted text
Sample code:

header file
```cpp

// other.h
class other {
public:
void abc();
void xyz();
void myFunction();
};

```

source file
```cpp
// other.cpp
#include "other.h"

void other::abc() {

}

void other::xyz() {

}
```

**Repro steps:**
1. Use sample files with sample code.
2. Invoke create declaration / definition command on function `myFunction()`.

**Result:** definition of `myFunction()` is created in file other.cpp. Extension navigates to file other.cpp but does not select and put cursor on the newly created definition of `myFunction()`.

**Expected result:** when navigating to the newly created definition or declaration, extension should select the newly inserted text.

### LINKED ISSUE #10161: Create declaration/definition feature should format newly inserted definition or declaration
1. Create declaration of a function.
2. Invoke create declaration / definition command on function declaration.

**Result:** the created definition is not format.

**Expected result:** the created definition should be formatted according to the format style specified in settings.

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fixes https://github.com/microsoft/vscode-cpptools/issues/10161, https://github.com/microsoft/vscode-cpptools/issues/10160.

Also https://github.com/microsoft/vscode-cpptools/issues/10164 for clang-format due to a by-product of its extra newline removal).

### CODE REVIEW

File: Extension/src/LanguageServer/client.ts [hunk 1]
```diff
@@ -2964,6 +2964,16 @@ export class DefaultClient implements Client {
         this.handleRemoveCodeAnalysisProblems(false, identifiersAndUris);
     }
 
+    private static countNewlines(text: string): number {
+        let numNewlines: number = 0;
+        for (let index: number = 0; index < text.length; ++index) {
```
Comment (bobbrow) [inline Extension/src/LanguageServer/client.ts]: Or you can do it without a loop:
`return (text.match(/\n/g) || []).length;`

File: Extension/src/LanguageServer/client.ts [hunk 2]
```diff
@@ -2964,6 +2964,16 @@ export class DefaultClient implements Client {
         this.handleRemoveCodeAnalysisProblems(false, identifiersAndUris);
     }
 
+    private static countNewlines(text: string): number {
```
Comment (bobbrow) [inline Extension/src/LanguageServer/client.ts]: Not sure that this needs to be a static function in a class.  It could just be a regular function outside a class (e.g. a "util" function).

File: Extension/src/LanguageServer/client.ts [hunk 3]
```diff
@@ -3013,8 +3027,34 @@ export class DefaultClient implements Client {
                 };
                 if (modifiedDocument && lastEdit) {
                     await vscode.workspace.applyEdit(workspaceEdit);
-                    const selectionRange: vscode.Range = lastEdit.range; // TODO: range should be the new range after text edit was applied.
+                    let numNewlines: number = DefaultClient.countNewlines(lastEdit.newText);
+
+                    // Move the cursor to the new code, accounting for \n or \n\n at the start.
+                    let selectionRange: vscode.Range = new vscode.Range(new vscode.Position(lastEdit.range.start.line + numNewlinesFromPreviousEdits, 0), new vscode.Position(lastEdit.range.start.line + numNewlinesFromPreviousEdits, 0));
```
Comment (bobbrow) [inline Extension/src/LanguageServer/client.ts]: Slightly more readable might be:
```ts
let startLine = lastEdit.range.start.line;
if (lastEdit.newText.startsWith("\r\n\r\n") || lastEdit.newText.startsWith("\n\n")) {
    startLine += 2;
    numNewlines -= 2;
} else if (lastEdit.newText.startsWith("\r\n") || lastEdit.newText.startsWith("\n")) {
    startLine += 1;
    numNewlines -= 1;
}
const selectionRange: vscode.Range = new vscode.Range(new vscode.Position(startLine + numNewlinesFromPreviousEdits, 0), new vscode.Position(startLine + numNewlinesFromPreviousEdits, 0));
```

**Review by bobbrow — DISMISSED** [review]
I'm fine with this.  Only cosmetic feedback.

File: Extension/src/LanguageServer/client.ts (hunk 1 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/client.ts]: Sure, that seems good to me.

File: Extension/src/LanguageServer/client.ts (hunk 3 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/client.ts]: I'll try that

**Comment by sean-mcmanus** [comment]
I'm still investigating a potential bug...

**Comment by sean-mcmanus** [comment]
@bobbrow There is a regression with selection formatting with 1.13.4 with clang-format 15, which can cause the formatting to fail with CDD. I'm looking into whether it's a clang-format bug or if it's some other change.

**Review by bobbrow — DISMISSED** [review]

**Comment by sean-mcmanus** [comment]
@bobbrow I pushed a minor fix of an issue I hit when using vcFormat.

**Review by Supsource — APPROVED** [review]

**Review by bobbrow — APPROVED** [review]

**Review by Colengms — APPROVED** [review]

**Review by michelleangela — APPROVED** [review]
