### PR TITLE
Fix "Command '' not found" error.

### LINKED ISSUE #8599: C/C++ parser displays "Command '' not found"
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1. Open c/c++ project.
2. Parser running
3. Click on parser status icon
4. "Command '' not found" error message

Extension version: 1.7.1
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.64GB (0.51GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/cuncon-wsl/projects/alink/SAL2 --remote=wsl+Ubuntu --crash-reporter-id 24a2238d-530f-4238-a634-5a8b8957f2a4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|Memory (System)|5.92GB (2.36GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|Memory (System)|5.92GB (2.36GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614
vscexrecpromp3t2:30407763

```

</details>

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fixes https://github.com/microsoft/vscode-cpptools/issues/8599

Existing code in other places sets no-op commands to "undefined".

### CODE REVIEW

File: Extension/src/LanguageServer/ui.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export class UI {
         this.browseEngineStatusBarItem.name = localize("c.cpp.tagparser.statusbar", "C/C++ Tag Parser Status");
         this.browseEngineStatusBarItem.text = "";
         this.browseEngineStatusBarItem.tooltip = localize("discovering.files.tooltip", "Discovering files");
-        this.browseEngineStatusBarItem.command = "";
+        this.browseEngineStatusBarItem.command = undefined;
```
Comment (bobbrow) [inline Extension/src/LanguageServer/ui.ts]: Does this need to be explicitly set to undefined, or can we just remove these assignment lines?

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/ui.ts]: Yeah, I removed a few unnecessary initialization lines.

**Review by bobbrow — APPROVED** [review]
