### PR TITLE
Fix show a list local processes, if remote connection failed (useExtendedRemote)

### LINKED ISSUE #12547: If the connection failed (useExtendedRemote), a list of local processes will be displayed
### Environment

- OS and version: Debian 11.6
- VS Code: 1.75.1
- C/C++ extension: 1.21.5
- GDB / LLDB version: gdb 10.1.90.20210103-git

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Create simple configureation in `launch.json`
2. We do not run the process gdbserver on a remote server.
3. Start debugging `remote attach`
4. If the connection failed, a list of local processes will be displayed. I was expecting to see an error message instead of a list of local process.

### Debugger Configurations

```shell
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "remote attach",
			"type": "cppdbg",
			"request": "attach",
			"program": "/home/stas/test_project/test",
			"MIMode": "gdb",
			"useExtendedRemote": true,
			"miDebuggerPath": "gdb",
			"miDebuggerServerAddress": "<any_ip>",
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				},
			],
			"logging": 
			{
				"trace": true,
    			"traceResponse": true,
    			"engineLogging": true
			}	
		},
	],
}
```
```


### Debugger Logs

```shell
Launch configuration:
{
  "name": "remote attach",
  "type": "cppdbg",
  "request": "attach",
  "program": "/home/stas/test_project/test",
  "MIMode": "gdb",
  "useExtendedRemote": true,
  "miDebuggerPath": "gdb",
  "miDebuggerServerAddress": "127.0.0.1:8888",
  "setupCommands": [
    {
      "description": "Enable pretty-printing for gdb",
      "text": "-enable-pretty-printing",
      "ignoreFailures": true
    }
  ],
  "logging": {
    "trace": true,
    "traceResponse": true,
    "engineLogging": true
  },
  "__configurationTarget": 6
}
pid        user       command    cores      
1          root       /sbin/init 0          
2          root       [kthreadd] 2          
3          root       [rcu_gp]   2          
4          root       [rcu_par_gp] 0          
6          root       [kworker/0:0H-ev] 0          
8          root       [mm_percpu_wq] 0          
9          root       [rcu_tasks_rude_] 0          
10         root       [rcu_tasks_trace] 0          
11         root       [ksoftirqd/0] 0          
12         root       [rcu_sched] 2          
13         root       [migration/0] 0          
14         root       [kworker/0:1-eve] 0          
15         root       [cpuhp/0]  0          
16         root       [cpuhp/1]  1          
17         root       [migration/1] 1          
18         root       [ksoftirqd/1] 1          
20         root       [kworker/1:0H-ev] 1          
21         root       [cpuhp/2]  2          
22         root       [migration/2] 2          
23         root       [ksoftirqd/2] 2          
25         root       [kworker/2:0H-ev] 2          
26         root       [cpuhp/3]  3          
27         root       [migration/3] 3          
28         root       [ksoftirqd/3] 3          
30         root       [kworker/3:0H-kb] 3          
35         root       [kdevtmpfs] 2          
36         root       [netns]    1          
37         root       [kauditd]  0          
38         root       [khungtaskd] 3          
39         root       [oom_reaper] 1          
40         root       [writeback] 3          
41         root       [kcompactd0] 0          
42         root       [ksmd]     3          
43         root       [khugepaged] 0          
61         root       [kintegrityd] 0          
62         root       [kblockd]  1          
63         root       [blkcg_punt_bio] 1          
64         root       [edac-poller] 3          
65         root       [devfreq_wq] 1          
67         root       [kworker/0:1H-kb] 0          
68         root       [kswapd0]  3          
69         root       [kthrotld] 1          
70         root       [acpi_thermal_pm] 3          
71         root       [ipv6_addrconf] 1          
74         root       [kworker/1:1-eve] 1          
82         root       [kstrp]    3          
85         root       [zswap-shrink] 1          
86         root       [kworker/u9:0] 3          
109        root       [kworker/2:1H-kb] 2          
136        root       [ata_sff]  2          
137        root       [scsi_eh_0] 3          
138        root       [scsi_tmf_0] 1          
139        root       [scsi_eh_1] 3          
140        root       [scsi_tmf_1] 1          
141        root       [kworker/1:1H-kb] 1          
143        root       [scsi_eh_2] 3          
144        root       [scsi_tmf_2] 1          
150        root       [kworker/3:1H-kb] 3          
152        root       [irq/18-vmwgfx] 2          
153        root       [ttm_swap] 2          
154        root       [card0-crtc0] 1          
155        root       [card0-crtc1] 1          
156        root       [card0-crtc2] 1          
157        root       [card0-crtc3] 1          
158        root       [card0-crtc4] 1          
159        root       [card0-crtc5] 1          
160        root       [card0-crtc6] 1          
161        root       [card0-crtc7] 2          
201        root       [jbd2/sda1-8] 1          
202        root       [ext4-rsv-conver] 2          
240        root       /lib/systemd/systemd-journald 3          
265        root       /lib/systemd/systemd-udevd 2          
325        root       [iprt-VBoxWQueue] 2          
333        root       /usr/sbin/haveged --Foreground --verbose=1 1          
335        root       [kworker/2:3-eve] 2          
413        root       /usr/libexec/accounts-daemon 0,3        
415        avahi      avahi-daemon: running [stas-deb.local] 3          
419        root       /usr/sbin/cron -f 1          
421        messagebus /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only 3          
424        root       /usr/sbin/NetworkManager --no-daemon 0,2        
428        root       /usr/libexec/polkitd --no-debug 0          
429        root       /usr/sbin/rsyslogd -n -iNONE 0,1,3      
430        root       /lib/systemd/systemd-logind 0          
431        root       /usr/libexec/udisks2/udisksd 0,1,2,3    
433        root       /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant 0          
434        avahi      avahi-daemon: chroot helper 2          
470        root       /usr/sbin/ModemManager 0,2        
479        root       /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal 1,2        
492        root       sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups 1          
507        root       /usr/sbin/apache2 -k start 3          
571        root       [cryptd]   2          
637        root       /usr/sbin/cupsd -l 3          
649        root       /usr/sbin/cups-browsed 1,2        
783        root       /usr/bin/sddm 2,3        
794        root       /usr/bin/VBoxDRMClient 0,1,2,3    
797        root       /usr/sbin/VBoxService --pidfile /var/run/vboxadd-service.sh 0,1,2,3    
814        root       /usr/lib/xorg/Xorg -nolisten tcp -auth /var/run/sddm/{ce3d7bbd-8846-45ac-8cbb-a38014fcd305} -background none -noreset -displayfd 17 -seat seat0 vt7 0,1,2,3    
832        www-data   /usr/sbin/apache2 -k start 0,1,2,3    
833        www-data   /usr/sbin/apache2 -k start 0,1,2,3    
891        root       /usr/lib/x86_64-linux-gnu/sddm/sddm-helper --socket /tmp/sddm-auth26ad9f45-9852-4d69-8182-ab29b455ab60 --id 1 --start /usr/bin/startplasma-x11 --user stas --autologin 0          
893        stas       /lib/systemd/systemd --user 0          
894        stas       (sd-pam)   3          
908        stas       /usr/bin/pipewire 3          
909        stas       /usr/bin/pulseaudio --daemonize=no --log-target=journal 0,2,3      
910        stas       /usr/bin/startplasma-x11 2,3        
914        rtkit      /usr/libexec/rtkit-daemon 1,2        
928        stas       /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only 1          
936        stas       /usr/bin/pipewire-media-session 1,3        
959        stas       /usr/bin/VBoxClient --clipboard 3          
960        stas       /usr/bin/VBoxClient --clipboard 2,3        
974        stas       /usr/bin/VBoxClient --seamless 0          
975        stas       /usr/bin/VBoxClient --seamless 0,1,3      
982        stas       /usr/bin/VBoxClient --draganddrop 3          
983        stas       /usr/bin/VBoxClient --draganddrop 1,3        
991        stas       /usr/bin/VBoxClient --vmsvga-session 3          
992        stas       /usr/bin/VBoxClient --vmsvga-session 0,1,2,3    
997        stas       /usr/bin/ssh-agent /usr/bin/startplasma-x11 1          
1001       stas       /usr/libexec/pulse/gsettings-helper 0,1,3      
1020       stas       /usr/lib/x86_64-linux-gnu/libexec/kf5/start_kdeinit 0          
1021       stas       kdeinit5: Running... 3          
1022       stas       /usr/lib/x86_64-linux-gnu/libexec/kf5/klauncher --fd=9 0,3        
1049       stas       /usr/bin/kded5 0,1,3      
1053       stas       /usr/bin/kwin_x11 0,2,3      
1078       stas       /usr/bin/kglobalaccel5 0,1,2      
1082       stas       /usr/lib/x86_64-linux-gnu/libexec/kactivitymanagerd 0,1,2      
1089       root       /usr/libexec/upowerd 1,2,3      
1092       stas       /usr/bin/ksmserver 0,2        
1187       stas       /usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 0,1,3      
1197       stas       /usr/bin/xembedsniproxy 0,1,3      
1208       stas       /usr/bin/plasmashell 0,1,2,3    
1223       stas       /usr/libexec/dconf-service 2          
1237       stas       /usr/bin/kaccess 0,1,2      
1243       stas       /usr/lib/x86_64-linux-gnu/libexec/DiscoverNotifier 0,1        
1247       stas       /usr/bin/xsettingsd 0          
1258       stas       /usr/bin/gmenudbusmenuproxy 0,3        
1263       stas       /usr/lib/x86_64-linux-gnu/libexec/kdeconnectd 0,2,3      
1318       root       /usr/libexec/packagekitd 0,2,3      
1349       stas       /usr/bin/korgac -session 10a0d8c6d5000167674382700000009760010_1722085035_231972 0,1,3      
1478       Debian-exim /usr/sbin/exim4 -bd -q30m 1          
1486       stas       /usr/libexec/at-spi-bus-launcher --launch-immediately 2,3        
1492       stas       /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3 3          
1493       stas       /usr/libexec/geoclue-2.0/demos/agent 3          
1499       stas       /usr/lib/x86_64-linux-gnu/libexec/org_kde_powerdevil 0,1,2,3    
1501       stas       /usr/bin/kup-daemon 0,3        
1532       stas       /usr/lib/x86_64-linux-gnu/libexec/kf5/kscreen_backend_launcher 0,1        
1533       stas       /usr/libexec/bluetooth/obexd 1          
1605       root       [kworker/2:4-eve] 2          
1606       stas       file.so [kdeinit5] file local:/run/user/1000/klauncherfWLknc.1.slave-socket local:/run/user/1000/kded5RVjyFz.1.slave-socket 1          
1995       stas       /usr/share/code/code --unity-launch --enable-crashpad 0,1,2,3    
1998       stas       /usr/share/code/code --type=zygote --no-zygote-sandbox --enable-crashpad --enable-crashpad 2          
1999       stas       /usr/share/code/code --type=zygote --enable-crashpad --enable-crashpad 1          
2001       stas       /usr/share/code/code --type=zygote --enable-crashpad --enable-crashpad 0          
2014       stas       /usr/share/code/chrome_crashpad_handler --monitor-self-annotation=ptype=crashpad-handler --no-rate-limit --database=/home/stas/.config/Code/Crashpad --url=appcenter://code?aid=fba07a4d-84bd-4fc8-a125-9640fc8ce171&uid=f68763cc-6a34-4409-8e9b-a7721cd0b9cd&iid=f68763cc-6a34-4409-8e9b-a7721cd0b9cd&sid=f68763cc-6a34-4409-8e9b-a7721cd0b9cd --annotation=IsOfficialBuild=1 --annotation=_companyName=Microsoft --annotation=_productName=VSCode --annotation=_version=1.75.1 --annotation=exe=/usr/share/code/code --unity-launch --enable-crashpad --annotation=lsb-release=Debian GNU/Linux 11 (bullseye) --annotation=plat=Linux --annotation=prod=Electron --annotation=ver=19.1.9 --initial-client-fd=41 --shared-client-connection 2,3        
2036       stas       /usr/libexec/xdg-desktop-portal 0,1,3      
2041       stas       /usr/libexec/xdg-document-portal 0,1,2,3    
2044       stas       /usr/libexec/xdg-permission-store 2,3        
2046       stas       /usr/share/code/code --type=gpu-process --enable-crashpad --crashpad-handler-pid=2014 --enable-crash-reporter=c1bbbce3-9468-45ea-98c8-4a735b149b03,no_channel --user-data-dir=/home/stas/.config/Code --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,16233810019450463559,7825762536876196356,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess 0,1,2,3    
2052       root       fusermount -o rw,nosuid,nodev,fsname=portal,auto_unmount,subtype=portal -- /run/user/1000/doc 1          
2059       stas       /usr/libexec/xdg-desktop-portal-gtk 0,2        
2073       stas       /usr/libexec/at-spi2-registryd --use-gnome-session 0          
2087       stas       /usr/share/code/code --type=utility --utility-sub-type=network.mojom.NetworkService --lang=ru --service-sandbox-type=none --enable-crashpad --crashpad-handler-pid=2014 --enable-crash-reporter=c1bbbce3-9468-45ea-98c8-4a735b149b03,no_channel --user-data-dir=/home/stas/.config/Code --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,16233810019450463559,7825762536876196356,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess --enable-crashpad 0,1,3      
2101       stas       /usr/share/code/code --type=renderer --enable-crashpad --crashpad-handler-pid=2014 --enable-crash-reporter=c1bbbce3-9468-45ea-98c8-4a735b149b03,no_channel --user-data-dir=/home/stas/.config/Code --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --app-path=/usr/share/code/resources/app --no-sandbox --no-zygote --enable-blink-features=HighlightAPI --lang=ru --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --launch-time-ticks=320927143 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,16233810019450463559,7825762536876196356,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess --vscode-window-config=vscode:ae6b19fe-0232-4f61-b140-7cd209f5dadd --enable-crashpad 0,1,2,3    
2129       stas       /usr/share/code/code --type=renderer --enable-crashpad --crashpad-handler-pid=2014 --enable-crash-reporter=c1bbbce3-9468-45ea-98c8-4a735b149b03,no_channel --user-data-dir=/home/stas/.config/Code --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --app-path=/usr/share/code/resources/app --no-sandbox --no-zygote --node-integration-in-worker --disable-gpu-compositing --lang=ru --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=5 --launch-time-ticks=322026396 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,16233810019450463559,7825762536876196356,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess --vscode-window-config=vscode:a8cea3e2-f7c4-4e54-a638-68c10ea67245 --vscode-window-kind=shared-process --enable-crashpad 0,1,2,3    
2157       stas       /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/out/bootstrap-fork --type=ptyHost --logsPath /home/stas/.config/Code/logs/20240805T215610 0,1,2,3    
2375       root       [kworker/1:0] 1          
2433       root       sshd: stas [priv] 3          
2440       stas       sshd: stas@notty 1          
2441       stas       /usr/lib/openssh/sftp-server 1          
2577       stas       /usr/share/code/code --type=utility --utility-sub-type=node.mojom.NodeService --lang=ru --service-sandbox-type=none --inspect-port=0 --enable-crashpad --crashpad-handler-pid=2014 --enable-crash-reporter=c1bbbce3-9468-45ea-98c8-4a735b149b03,no_channel --user-data-dir=/home/stas/.config/Code --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,16233810019450463559,7825762536876196356,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess --enable-crashpad 1,2,3      
2587       stas       /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/out/bootstrap-fork --type=fileWatcher 0,1,2,3    
2613       stas       /usr/share/code/code --ms-enable-electron-run-as-node /home/stas/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.42.0/out/server.js --node-ipc --clientProcessId=2577 0,1,2,3    
2633       stas       /home/stas/.vscode/extensions/ms-vscode.cpptools-1.21.5-linux-x64/bin/cpptools 0,1,2,3    
2648       stas       /usr/share/code/code --ms-enable-electron-run-as-node /home/stas/.vscode/extensions/streetsidesoftware.code-spell-checker-2.20.3/packages/_server/dist/main.js --node-ipc --clientProcessId=2577 0,1,2,3    
2657       stas       /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=2577 0,1,2      
2709       root       [kworker/3:3-eve] 3          
2971       root       [kworker/3:1] 3          
3016       stas       konqueror [kdeinit5] --mimetype text/html https://code.visualstudio.com/ 0,1,2,3    
3035       stas       /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess --type=zygote --no-zygote-sandbox --application-name=konqueror --webengine-schemes=error:lL;konq:lL;info:lL;about:lL;ghelp:lL;man:lL;help:lL;qrc:sLV --lang=ru 3          
3036       stas       /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess --type=zygote --application-name=konqueror --webengine-schemes=error:lL;konq:lL;info:lL;about:lL;ghelp:lL;man:lL;help:lL;qrc:sLV --lang=ru 2          
3038       stas       /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess --type=zygote --application-name=konqueror --webengine-schemes=error:lL;konq:lL;info:lL;about:lL;ghelp:lL;man:lL;help:lL;qrc:sLV --lang=ru 2          
3059       stas       /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess --type=utility --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FontSrcLocalMatching,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --lang=ru --service-sandbox-type=network --use-gl=desktop --application-name=konqueror --webengine-schemes=error:lL;konq:lL;info:lL;about:lL;ghelp:lL;man:lL;help:lL;qrc:sLV --shared-files 0,1        
3080       stas       /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FontSrcLocalMatching,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --lang=ru --webengine-schemes=error:lL;konq:lL;info:lL;about:lL;ghelp:lL;man:lL;help:lL;qrc:sLV --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=5 --shared-files 1,2,3      
3113       stas       /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess --type=utility --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FontSrcLocalMatching,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --lang=ru --service-sandbox-type=audio --use-gl=desktop --application-name=konqueror --webengine-schemes=error:lL;konq:lL;info:lL;about:lL;ghelp:lL;man:lL;help:lL;qrc:sLV --shared-files 1,2        
3242       stas       /usr/bin/dolphin 0,1,2,3    
3452       root       [kworker/0:2-ata] 0          
3462       stas       /usr/bin/krunner 0,1,2,3    
3500       stas       /usr/bin/konsole 0,1,2,3    
3519       stas       /bin/bash  2          
3523       root       [kworker/u8:1-fl] 3          
3524       root       [kworker/u8:2-ex] 1          
3574       root       [kworker/0:0-ata] 0          
3626       stas       /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh 3          
3712       root       [kworker/u8:0-fl] 2          
3752       stas       /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/out/bootstrap-fork ms-vscode.cppdbg {"common.vscodemachineid":"4e43364347ad536d3654237180ad15fcd9e9902748834961df1afe85a488f7e2","common.vscodesessionid":"f0d881ab-3932-497b-9f38-fa16384cb6d41722884172068"} 0c6ae279ed8443289764825290e4f9e2-1a736e7c-1324-4338-be46-fc2a58ae4d14-7255 0,1,2,3    
3784       stas       /bin/sh -c gdb -ex "target extended-remote 127.0.0.1:8888" -ex "info os processes" -batch 1          
3785       stas       gdb -ex target extended-remote 127.0.0.1:8888 -ex info os processes -batch 0,1,2,3
```

### Other Extensions

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MrStanislav0**
Hello, I fixed https://github.com/microsoft/vscode-cpptools/issues/12547 

The problem was that there was a connection error (`-ex "target extended-remote 192.168.1.1:8888"`) and the command to list the processes was executed (` -ex "info os processes"`)
Command run gdb: `gdb -ex "target extended-remote 192.168.1.1:8888" -ex "info os processes" -batch`
 
If the connection failed, an error message will be displayed.

### CODE REVIEW

**Comment by MrStanislav0** [comment]
@microsoft-github-policy-service agree

**Review by fearthecowboy — APPROVED** [review]
Looks ok to me.

File: Extension/src/Debugger/attachToProcess.ts [hunk 1]
```diff
@@ -187,13 +187,18 @@ export class RemoteAttachPicker {
...
+        for (let i: number = 0; i < 5 && !processListOutput.succeeded && processListOutput.outputError.length === 0; i++) {
             processListOutput = await util.spawnChildProcess(miDebuggerPath, args);
         }
 
         if (!processListOutput.succeeded) {
             throw new Error(localize('failed.to.make.gdb.connection', 'Failed to make GDB connection: "{0}".', processListOutput.output));
         }
+
+        if (processListOutput.outputError.length !== 0) {
+            throw new Error(localize('failed.to.make.gdb.connection', 'Failed to make GDB connection: "{0}".', processListOutput.outputError));
```
Comment (sean-mcmanus) [inline Extension/src/Debugger/attachToProcess.ts:199]: @bobbrow @Colengms Is 2 of the same loc string okay? Do does the label need to be different?

Comment (sean-mcmanus) [reply Extension/src/Debugger/attachToProcess.ts:199]: Oh, I see 2 of the same loc label in other files, so it seems like it's okay.

File: Extension/src/common.ts [hunk 2]
```diff
@@ -775,7 +776,7 @@ export async function spawnChildProcess(program: string, args: string[] = [], co
         } else {
             stdout = localize('process.succeeded', 'Process executed successfully.');
         }
-        return { succeeded: true, exitCode, output: stdout };
+        return { succeeded: true, exitCode, outputError: programOutput.stderr, output: stdout };
```
Comment (sean-mcmanus) [inline Extension/src/common.ts:779]: It seems a little odd for the outputError named parameter to not be the last one since it's the last declared, but I'm not sure if that matters or not.

**Review by sean-mcmanus — APPROVED** [review]

File: Extension/src/Debugger/attachToProcess.ts (hunk 1 above)
Comment (bobbrow) [reply Extension/src/Debugger/attachToProcess.ts:199]: It is ok if the string is identical in both uses.  Otherwise, you may not get the string you expect.

File: Extension/src/common.ts (hunk 2 above)
Comment (bobbrow) [reply Extension/src/common.ts:779]: The order shouldn't matter.
