### PR TITLE
Fixes to compile commands file watchers fallback logic

### LINKED ISSUE #12946: Compile commands file watchers are leaked without being closed
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.95.1
- C/C++ Extension Version: V1.22.11
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

**Bug Summary:**

When using `compileCommands` in a configuration, deleting the json file causes the fallback function `checkCompileCommands()` in `src\LanguageServer\configurations.ts` to dispose the file watchers without closing them.

**Steps to reproduce:**
1. Use the `compileCommands` configuration with a path to a `compile_commands.json`.
2. Update the file's timestamp. (`touch` it or compile a CMake project which updates it)
   - `CppProperties.compileCommandsFile` is updated with a value.
4. Delete or rename the file.
5. next periodic call to `checkCompileCommands()` will enter the error case and leak the file watchers.  
```cpp
// in checkCompileCommands()
fs.stat(compileCommandsFile, (err, stats) => {
    if (err) {
        if (err.code === "ENOENT" && this.compileCommandsFile) {
            // file watchers should be closed here
            this.compileCommandsFileWatchers = []; // reset file watchers
```
  
**Expected behavior:**
`checkCompileCommands()` should close the file watchers before disposing.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "compdb1",
            "compileCommands": "${workspaceFolder}/compile_commands_1.json",
            "intelliSenseMode": "windows-msvc-x64",
            "cStandard": "c17",
            "cppStandard": "c++17"
        },
        {
            "name": "compdb2",
            "compileCommands": "${workspaceFolder}/compile_commands_2.json",
            "intelliSenseMode": "linux-gcc-x64",
            "cStandard": "c17",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

### Other Extensions

_No response_

### Additional context

_No response_

### LINKED ISSUE #12947: Compile commands fallback logic can miss changes when using multiple configurations with different `compile_commands.json` paths
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.95.1
- C/C++ Extension Version: V1.22.11
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

**Bug Summary:**
Assuming file watchers have failed/closed, the fallback logic `CppProperties.checkCompileCommands` can fail to detect changes in a `compile_commands.json` from a different configuration index (even when later switching to that configuration index)

**Steps to reproduce:**
Assume the following `c_cpp_properties.json` (only relevant parts shown)
```json
{
    "configurations": [
        {
            "name": "compdb1",
            "compileCommands": "${workspaceFolder}/compile_commands_1.json",
        },
        {
            "name": "compdb2",
            "compileCommands": "${workspaceFolder}/compile_commands_2.json",
        }
    ],
    "version": 4
}
```
1. Assume we are using `compdb1`
2. Assume file watchers failed/closed on any of the example reasons:
    - We can force the file watchers to be closed by reproducing the steps described in #12946.
    - `fs.watch` loses track of the file on `Linux` if file is deleted/doesn't exist. (on `Linux`, `fs.watch` tracks by `inode`)
    - Failed to create a file watcher by crossing the `inotify` limit on `Linux`.
3. Update `compile_commands_2.json` (by `touch`ing or actually compiling some `CMake` project)
   - Assuming file watchers are closed/failed, no event is triggered on this change.
   - `checkCompileCommands()` only checks the file used by the current configuration, no event is triggered on this change.
4. Update `compile_commands_1.json`
   - Now, `compile_commands_1.json` is newer than `compile_commands_2.json`.
   - `CppProperties.compileCommandsFileWatcherFallbackTime` is assigned `compile_commands_1.json`'s timestamp.
5. Switch to `compdb2`
   - File watchers are re-created, but no event is triggered as `compile_commands_2.json` has changed before re-initializing the file watchers.
   -  `CppProperties.compileCommandsFileWatcherFallbackTime` is a newer timestamp than `compile_commands_2.json`'s timestamp, so `checkCompileCommands()` does not trigger an event.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "compdb1",
            "compileCommands": "${workspaceFolder}/compile_commands_1.json",
        },
        {
            "name": "compdb2",
            "compileCommands": "${workspaceFolder}/compile_commands_2.json",
        }
    ],
    "version": 4
}
```

### Other Extensions

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yiftahw**
- closes #12946 
    - File watchers are closed before being disposed.
- closes #12947 
    - Changed the fallback timestamp `CppProperties.compileCommandsFileWatcherFallbackTime` to be a `Map<string, Date>` which keeps track of a timestamp per file instead of a single one.

### CODE REVIEW

File: Extension/src/LanguageServer/configurations.ts [hunk 1]
```diff
@@ -2307,15 +2330,17 @@ export class CppProperties {
...
             if (err) {
                 if (err.code === "ENOENT" && this.compileCommandsFile) {
+                    this.compileCommandsFileWatchers.forEach((watcher: fs.FSWatcher) => watcher.close());
                     this.compileCommandsFileWatchers = []; // reset file watchers
                     this.onCompileCommandsChanged(compileCommandsFile);
                     this.compileCommandsFile = null; // File deleted
                 }
-            } else if (stats.mtime > this.compileCommandsFileWatcherFallbackTime) {
-                this.compileCommandsFileWatcherFallbackTime = new Date();
+            } else if (compileCommandsLastChanged !== undefined && stats.mtime > compileCommandsLastChanged) {
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts]: Can you change it to call `this.compileCommandsFileWatcherFallbackTime.get(compileCommandsFile)` in the stat callback? e.g.

```TypeScript
} else {
    const compileCommandsLastChanged: Date | undefined = this.compileCommandsFileWatcherFallbackTime.get(compileCommandsFile);
    if (compileCommandsLastChanged !== undefined && stats.mtime > compileCommandsLastChanged) {
...
```

**Review by sean-mcmanus — CHANGES_REQUESTED** [review]

File: Extension/src/LanguageServer/configurations.ts (hunk 1 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts]: Other than that it seems good to me.

Comment (yiftahw) [reply Extension/src/LanguageServer/configurations.ts]: @sean-mcmanus fixed

**Review by sean-mcmanus — APPROVED** [review]

**Review by Colengms — APPROVED** [review]
