### PR TITLE
Fix 'Extract to function' formatting/selection bugs.

### LINKED ISSUE #11614: 'Extract to function' doesn't correctly format the header declaration
It invokes the formatter on the header, but something is causing the formatting to not work as expected. I don't think this repros with VS (but I haven't checked). This repros with 1.18.0 and 1.18.1.

Repro is like

test.cpp
```cpp
namespace foo {
int main()
{
    return 0; // extract to function on this line
}
```

test.h
```
namespace foo
{
    int otherFunc();
}
```

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fixes https://github.com/microsoft/vscode-cpptools/issues/11614 (incorrect header formatting) and https://github.com/microsoft/vscode-cpptools/issues/11619 (incorrect selection) and fixes other unreported issues (e.g. duplicate formatting calls and unnecessary document switching).

### CODE REVIEW

File: Extension/src/LanguageServer/client.ts [hunk 1]
```diff
@@ -3497,7 +3497,8 @@ export class DefaultClient implements Client {
         let workspaceEdits: vscode.WorkspaceEdit = new vscode.WorkspaceEdit();
         let replaceEditRange: vscode.Range | undefined;
         let hasProcessedReplace: boolean = false;
-        const formatUriAndRanges: VsCodeUriAndRange[] = [];
+        const sourceFormatUriAndRanges: VsCodeUriAndRange[] = [];
```
Comment (bobbrow) [inline Extension/src/LanguageServer/client.ts:3503]: Maybe add a comment here explaining that this is not necessarily a "source" file.  It could be a header if the codeAction originated from there.

**Review by bobbrow — DISMISSED** [review]

File: Extension/src/LanguageServer/client.ts (hunk 1 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/client.ts:3503]: @bobbrow I added a comment.

**Review by bobbrow — APPROVED** [review]
