### PR TITLE
Fix for input delays when editing c_cpp_properties.json

### LINKED ISSUE #13591: Freeze/delayed input when editing c_cpp_properties.json
### Environment

- Windows 10 Enterprise 22H2
- VS Code Version: 1.99.3
- C/C++ Extension Version: 1.25.3

### Bug Summary and Steps to Reproduce

Bug Summary: When I edit c_cpp_properties.json it freezes, i.e. the next input is often delayed (5 to 15 seconds). This happens after every few keystrokes. Our codebase has around 8000 C/C++ files with 2 million lines of code.

Steps to reproduce:
See summary.

Expected behavior: No input delay when editing c_cpp_properties.json.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**/Interfaces/**",
                "${workspaceFolder}/**/BxPackaging/**",
                "${workspaceFolder}/**/DeveloperTools/**",
                "${workspaceFolder}/**/RuntimeExtensions/**",
                "${workspaceFolder}/**/Biometrics/**",
                "${workspaceFolder}/**/DataBinding/**",
                "${workspaceFolder}/**/Utility/**"
            ],
            "defines": [
                "WIN32"
            ],
            "windowsSdkVersion": "10.0.22621.0",
            "compilerPath": "cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "windows-msvc-x64",
            "compilerArgs": [
                "/std:c++11"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**/Interfaces/**",
                    "${workspaceFolder}/**/BxPackaging/**",
                    "${workspaceFolder}/**/DeveloperTools/**",
                    "${workspaceFolder}/**/RuntimeExtensions/**",
                    "${workspaceFolder}/**/Biometrics/**",
                    "${workspaceFolder}/**/DataBinding/**",
                    "${workspaceFolder}/**/Utility/**"
                ],
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}
```

### Other Extensions

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bobbrow**
Fixes: #13591

Some glob operations may be more expensive than users expect. This change does the glob processing async so that other work can continue. As a bonus, I added a performance warning squiggle for when glob path resolution takes more than 10 seconds as this may be unexpected.

### CODE REVIEW

File: Extension/src/LanguageServer/configurations.ts [hunk 1]
```diff
@@ -280,21 +278,21 @@ export class CppProperties {
         });
 
         vscode.workspace.onDidChangeTextDocument((e) => {
-            if (e.document.uri.fsPath === settingsPath && this.isCppPropertiesJsonVisible) {
+            if (e.document.uri.fsPath === settingsPath) {
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts:282]: I'm seeing this get called 4 times for every edit -- should we save/check the document version? Seems like it would be a pre-existing issue though, maybe a VS Code bug?

File: Extension/src/LanguageServer/configurations.ts [hunk 2]
```diff
@@ -846,7 +846,7 @@ export class CppProperties {
             if (isGlobPattern) {
                 // fastGlob silently strips non-found paths. Limit that behavior to dynamic paths only.
                 const matches: string[] = fastGlob.isDynamicPattern(normalized) ?
-                    fastGlob.sync(normalized, { onlyDirectories: true, cwd, suppressErrors: true, deep: 15 }) : [res];
+                    await fastGlob.async(normalized, { onlyDirectories: true, cwd, suppressErrors: true, deep: 15 }) : [res];
                 resolvedGlob.push(...matches.map(s => s + suffix));
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts:851]: I'm seeing this accumulate 6 fastGlob work tasks per edit for a big `**`...maybe that's a pre-existing issue? Shouldn't it cancel the previous ones that aren't needed?

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:851]: ...and when that occurs I don't see a timing warning.

Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts:851]: I'm seeing TypeScript fail with 

```
RangeError: Maximum call stack size exceeded
    at CppProperties.resolveAndSplit
```

on line 850 when this is >146k.

```TypeScript
resolvedGlob.push(...matches.map(s => s + suffix));
```

but that might be pre-existing...I haven't checked yet, but the user doesn't see any warning in that case and it seems like we want to fix that?

File: Extension/src/LanguageServer/configurations.ts (hunk 1 above)
Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts:282]: I updated the code to debounce this

File: Extension/src/LanguageServer/configurations.ts (hunk 2 above)
Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts:851]: It should be improved with the new debouncing logic, but I'll open a bug to investigate further.

Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts:851]: I didn't change anything here. Are you saying that the performance warning doesn't appear in this case because of the exception?

Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts:851]: I don't have your repro but pushed a change that might handle it. Could you try again?

File: Extension/src/LanguageServer/configurations.ts [hunk 3]
```diff
@@ -1712,7 +1724,26 @@ export class CppProperties {
...
+     * @param operation The async operation to perform.
+     * @returns The result of the operation and the time it took to complete in seconds.
+     */
+    private async timeOperation<T>(operation: () => Promise<T | undefined>): Promise<{ result: T | undefined; duration: number }> {
+        let result: T | undefined;
+        const start = process.hrtime();
+        try {
+            result = await operation();
+        } catch {
+            // Suppress errors
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts]: When this is hit, it shows the timing warning instead of an error message. Can you show an error message instead?

**Review by sean-mcmanus — CHANGES_REQUESTED** [review]

File: Extension/src/LanguageServer/configurations.ts (hunk 3 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts]: Maybe return a result of -1 or something and have the handler check that? Otherwise, it makes it seems like it worked but was slow, when it's really failing.

Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts]: Sure. I had thought that showing the timing warning would be a hint that the glob was too big, but I agree the error would probably be better.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts]: I guess it could be warning level though, something like "Path failed to be evaluated.".

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts]: Might be useful to track failures in telemetry too, to prioritize potentially fixes.

Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts]: The real challenge here is that `result` is of type `T` which isn't always a string. I'll probably have to catch the error at the place this is called instead.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts]: I was suggesting to just show a generic error message and not something specific, i.e. just to signal it was an error instead of a normal timeout.

File: Extension/src/LanguageServer/configurations.ts [hunk 4]
```diff
@@ -1834,7 +1866,22 @@ export class CppProperties {
         return errorMsg;
     }
 
-    private async handleSquiggles(): Promise<void> {
+    private lastConfigurationVersion: number = 0;
+    private handleSquigglesDeferral: Deferral | undefined;
+
+    private handleSquiggles(doc?: vscode.TextDocument): void {
+        // When the active config changes, we don't pass the doc in since the version would not have changed.
+        if (doc?.version !== this.lastConfigurationVersion) {
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts:1873]: I'm seeing this cause no error squiggles to appear after the doc is closed/reopened.

File: Extension/src/LanguageServer/configurations.ts [hunk 5]
```diff
@@ -846,7 +847,7 @@ export class CppProperties {
             if (isGlobPattern) {
                 // fastGlob silently strips non-found paths. Limit that behavior to dynamic paths only.
                 const matches: string[] = fastGlob.isDynamicPattern(normalized) ?
-                    fastGlob.sync(normalized, { onlyDirectories: true, cwd, suppressErrors: true, deep: 15 }) : [res];
+                    await fastGlob.async(normalized, { onlyDirectories: true, cwd, suppressErrors: true, deep: 15 }) : [res];
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/configurations.ts:850]: I'm still seeing this called 3 times with an edit/save. I'm not sure why.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:850]: this.handleConfigurationChange(); is being called 2 times. The other call is from handleSquigglesImpl .

File: Extension/src/LanguageServer/configurations.ts (hunk 3 above)
Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts]: Yeah, that can't be done here. It needs to be done at the place this is called.

File: Extension/src/LanguageServer/configurations.ts (hunk 5 above)
Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts:850]: I wasn't fixing handleConfigurationChange in this PR. There will still be some duplicate calls.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:850]: I think it's due to auto-save, the edit triggers one handleConfigurationChange and the save triggers another.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:850]: Ok, I was wrong, disabling auto save, I see it trigger handleConfigurationChange  0 times on edit and 2 times on save.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:850]: I'm guessing a format on save might be happening.

File: Extension/src/LanguageServer/configurations.ts (hunk 4 above)
Comment (bobbrow) [reply Extension/src/LanguageServer/configurations.ts:1873]: Sometimes I can't get `onDidOpenTextDocument` to fire, but I updated it to not pass the doc in here so that squiggles will always process on document open.

File: Extension/src/LanguageServer/configurations.ts (hunk 3 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts]: Yeah, I meant to return an error result time hear and have the logging place check that.

File: Extension/src/LanguageServer/configurations.ts (hunk 4 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:1873]: I still don't see the timing squiggle though on reopen.

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:1873]: Ah, it's because it was < 10 sec.

File: Extension/src/LanguageServer/configurations.ts (hunk 3 above)
Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts]: Ok, I see it show the error now.

**Review by sean-mcmanus — APPROVED** [review]

**Review by sean-mcmanus — APPROVED** [review]
