### PR TITLE
Fix regression with environment variable defines.

### LINKED ISSUE #8695: invalid define when using custom env.variable
Bug type: Language Service

**Describe the bug**
版本: 1.64.0-insider (system setup)
提交: 16856037e075275f53b25b7e2dec2303e8e25728
日期: 2022-01-19T05:15:25.456Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
c/c++: 1.8.0

**To Reproduce**

- there is the c_cpp_properties.json

```json
{
 "env": {
        "MDK_DEFINES": [
            "__CC_ARM",
            "__arm__",
            "__align(x)=",
            "__ALIGNOF__(x)=",
            "__alignof__(x)=",
            "__asm(x)=",
            "__forceinline=",
            "__restrict=",
            "__global_reg(n)=",
            "__inline=",
            "__int64=long long",
            "__INTADDR__(expr)=0",
            "__irq=",
            "__packed=",
            "__pure=",
            "__smc(n)=",
            "__svc(n)=",
            "__svc_indirect(n)=",
            "__svc_indirect_r7(n)=",
            "__value_in_regs=",
            "__weak=",
            "__writeonly=",
            "__declspec(x)=",
            "__attribute__(x)=",
            "__nonnull__(x)=",
            "__register=",
            "__breakpoint(x)=",
            "__cdp(x,y,z)=",
            "__clrex()=",
            "__clz(x)=0U",
            "__current_pc()=0U",
            "__current_sp()=0U",
            "__disable_fiq()=",
            "__disable_irq()=",
            "__dmb(x)=",
            "__dsb(x)=",
            "__enable_fiq()=",
            "__enable_irq()=",
            "__fabs(x)=0.0",
            "__fabsf(x)=0.0f",
            "__force_loads()=",
            "__force_stores()=",
            "__isb(x)=",
            "__ldrex(x)=0U",
            "__ldrexd(x)=0U",
            "__ldrt(x)=0U",
            "__memory_changed()=",
            "__nop()=",
            "__pld(...)=",
            "__pli(...)=",
            "__qadd(x,y)=0",
            "__qdbl(x)=0",
            "__qsub(x,y)=0",
            "__rbit(x)=0U",
            "__rev(x)=0U",
            "__return_address()=0U",
            "__ror(x,y)=0U",
            "__schedule_barrier()=",
            "__semihost(x,y)=0",
            "__sev()=",
            "__sqrt(x)=0.0",
            "__sqrtf(x)=0.0f",
            "__ssat(x,y)=0",
            "__strex(x,y)=0U",
            "__strexd(x,y)=0",
            "__strt(x,y)=",
            "__swp(x,y)=0U",
            "__usat(x,y)=0U",
            "__wfe()=",
            "__wfi()=",
            "__yield()=",
            "__vfp_status(x,y)=0"
        ],
        "KEIL_C51_DEFINES": [
            "reentrant=",
            "compact=",
            "small=",
            "large=",
            "data=",
            "idata=",
            "pdata=",
            "bdata=",
            "xdata=",
            "code=",
            "bit=char",
            "sbit=char",
            "sfr=char",
            "sfr16=int",
            "sfr32=int",
            "interrupt=",
            "using=",
            "_at_==",
            "_priority_=",
            "_task_="
        ]
    },
    "configurations": [
        {
            //^ 此配置适合cortexm 结合vscode进行编辑
            "name": "CortexM",
            "includePath": [
                "${default}",
                "${workspaceFolder}/**",
                //! 以下路径建议你也把keil 安装到这个 地方
                "C:\\Keil_v5\\ARM\\ARMCC\\include",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\rw",
                "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.8.0\\CMSIS\\**"
            ],
            "defines": [
                "${env.MDK_DEFINES}" // 
            ],
            "intelliSenseMode": "windows-msvc-arm"
        }
    ],
    "version": 4
}
```
- errMsg

```
[{
	"resource": "/f:/ATCProjectFiles/MCU/AC7840x/HQA/code/HQA/driver/ckgen/ckgen_drv.c",
	"owner": "C/C++",
	"code": "992",
	"severity": 8,
	"message": "命令行错误: 宏定义无效: __CC_ARM;__arm__;__align(x)=;__ALIGNOF__(x)=;__alignof__(x)=;__asm(x)=;__forceinline=;__restrict=;__global_reg(n)=;__inline=;__int64=long long;__INTADDR__(expr)=0;__irq=;__packed=;__pure=;__smc(n)=;__svc(n)=;__svc_indirect(n)=;__svc_indirect_r7(n)=;__value_in_regs=;__weak=;__writeonly=;__declspec(x)=;__attribute__(x)=;__nonnull__(x)=;__register=;__breakpoint(x)=;__cdp(x,y,z)=;__clrex()=;__clz(x)=0U;__current_pc()=0U;__current_sp()=0U;__disable_fiq()=;__disable_irq()=;__dmb(x)=;__dsb(x)=;__enable_fiq()=;__enable_irq()=;__fabs(x)=0.0;__fabsf(x)=0.0f;__force_loads()=;__force_stores()=;__isb(x)=;__ldrex(x)=0U;__ldrexd(x)=0U;__ldrt(x)=0U;__memory_changed()=;__nop()=;__pld(...)=;__pli(...)=;__qadd(x,y)=0;__qdbl(x)=0;__qsub(x,y)=0;__rbit(x)=0U;__rev(x)=0U;__return_address()=0U;__ror(x,y)=0U;__schedule_barrier()=;__semihost(x,y)=0;__sev()=;__sqrt(x)=0.0;__sqrtf(x)=0.0f;__ssat(x,y)=0;__strex(x,y)=0U;__strexd(x,y)=0;__strt(x,y)=;__swp(x,y)=0U;__usat(x,y)=0U;__wfe()=;__wfi()=;__yield()=;__vfp_status(x,y)=0",
	"source": "C/C++",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```

"defines": [
    "${env.MDK_DEFINES}" // 
],
**Expected behavior**

**Screenshots**
image

**Additional context**
```json

```

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fix https://github.com/microsoft/vscode-cpptools/issues/8695 , regression caused by https://github.com/microsoft/vscode-cpptools/pull/8661 .

### CODE REVIEW

File: Extension/src/common.ts [hunk 1]
```diff
@@ -304,7 +304,7 @@ export function resolveCachePath(input: string | undefined, additionalEnvironmen
     return resolvedPath;
 }
 
-export function resolveVariables(input: string | undefined, additionalEnvironment?: { [key: string]: string | string[] }): string {
+export function resolveVariables(input: string | undefined, additionalEnvironment?: { [key: string]: string | string[] }, arrayResults?: string[]): string {
```
Comment (bobbrow) [inline Extension/src/common.ts:309]: Is there a better way to do this besides mutating args? In TypeScript I feel like we almost always treat args as `const` despite there being no syntax to specify that.  Maybe we should return `string | string[]` based on a bool arg that instructs us whether to join arrays or not.  It just "feels" wrong in this function to return results both in the args and from the function result.

Comment (bobbrow) [reply Extension/src/common.ts:309]: Another option is to return `{result, arrayResults}` if you want to continue to do an either-or. You'll just need to update the callers.

Comment (sean-mcmanus) [reply Extension/src/common.ts:309]: I think this is the best approach. I considered returning a string[]. There's absolutely nothing wrong with adding to the arrayResults object. It's the same as passing a vector by non-const reference in C++ and having the method insert stuff. I didn't want to have to change any of the (many) existing callers of resolveVariables that expect only a string to be returned.

Comment (bobbrow) [reply Extension/src/common.ts:309]: If you keep it this way, please document the function and the side effects that happen to the arg.  It is my opinion that not wanting to update callers is not a good reason to do it this way.

Comment (sean-mcmanus) [reply Extension/src/common.ts:309]: I added a comment. Only 1 out of the 24 callers of resolveVariables uses the arrayResults, so I didn't want to potentially risk breaking the other 23 callers and/or have to mess with changing all the usages.

Comment (bobbrow) [reply Extension/src/common.ts:309]: The comment is incorrect. A `string[]` result has always been possible, but would be returned as a delimited string instead.  The comment should say that if the caller needs array results returned as an array instead of a delimited string, use the `arrayResults` parameter to provide a location for the non-joined array results.

And on that note, `newValue` could be set the same in both cases. It's just an alternate form of the result.

Comment (sean-mcmanus) [reply Extension/src/common.ts:309]: No, the previous result was string and not string[]. A delimited string is not a string[].

I intentionally set newValue to "" if it's not used.

Comment (bobbrow) [reply Extension/src/common.ts:309]: I think you misunderstood my comment. The `string[]` result I'm referring to is packed as a `;` delimited string to match the return type and unpacked later. It's still a `string[]` at heart.

Comment (bobbrow) [reply Extension/src/common.ts:309]: What I'm trying to say is that the comment should indicate that when `arrayResults` is passed, a `string[]` result should be returned as its intended type (a `string[]`) instead of a `;` or `:` delimeted `string` and that result is copied into `arrayResults`.

Comment (sean-mcmanus) [reply Extension/src/common.ts:309]: I'm expecting the reader to interpret "string[]" as a reference to the literal type and not a reference to a "string" that is a "string[] at heart". There is no need to refer to any details about the contents of the strings.

Comment (bobbrow) [reply Extension/src/common.ts:309]: The way I read the comment, it was confusing. Can you just change it to this and I'll resolve the comment?

`Pass in 'arrayResults' if a string[] result is possible and a delimited string result is undesirable. The string[] result will be copied into 'arrayResults'.`

Comment (sean-mcmanus) [reply Extension/src/common.ts:309]: Sure

**Review by bobbrow — APPROVED** [review]
