### PR TITLE
Workaround for webViewPanel.postMessage getting dropped.

### LINKED ISSUE #7641: Edit Configuration (UI) is sometimes blank with VS Code 1.56
Bug type: General

**Describe the bug**
版本: 1.56.2 (system setup)
提交: 054a9295330880ed74ceaedda236253b4f39a335
日期: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.14393

- C/C++ Extension Version: 1.4.0

**To Reproduce**
*Please include code sample and `task.json` files.*
CPP_TOOL

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Fixes https://github.com/microsoft/vscode-cpptools/issues/7641 . Workaround for VS Code regression bug https://github.com/microsoft/vscode/issues/125546 .

VS Code can take up to 6 seconds to respond to the postMessage requests (i.e. it could retry around 10 times).

### CODE REVIEW

**Review by michelleangela — APPROVED** [review]

File: Extension/src/LanguageServer/configurations.ts [hunk 1]
```diff
@@ -1025,14 +1025,21 @@ export class CppProperties {
...
                             }
-                        },
-                        500); // Need some delay or the UI can randomly be blank, particularly in the remote scenario.
+                            this.settingsPanel.updateConfigUI(configNames,
+                                this.configurationJson.configurations[this.settingsPanel.selectedConfigIndex],
+                                this.getErrorsForConfigUI(this.settingsPanel.selectedConfigIndex));
+
+                            // Need to queue another update due to a VS Code regression bug which may drop the initial update.
+                            // It repros with a higher probability in cases that cause a slower load, such as after
+                            // switching to a Chinese langauge pack or in the remote scenario.
```
Comment (jogo-) [inline Extension/src/LanguageServer/configurations.ts:1038]: Typo: lang**au**ge -> lang**ua**ge

Comment (sean-mcmanus) [reply Extension/src/LanguageServer/configurations.ts:1038]: Good catch -- I had removed the comment because the code was deleted, but I decided to add it back (with the typo fixed): https://github.com/microsoft/vscode-cpptools/pull/7656
