### PR TITLE
Fix buffer size exceeded with NativeAttach

### LINKED ISSUE #10107: Debugger throws error "stdout maxBuffer exceeded"
Type: <b>Bug</b>

1. Open a c++ project
2. Set up your launch.json. Th debug task specifies the process ID as  "processId":"${command:pickProcess}".
3. Run -> Start Debugging
4. The error "stdout maxBuffer exceeded is thrown"

Extension version: 1.12.4
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.76.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.76.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.34GB free)|
|Process Argv|--crash-reporter-id 786768c0-d188-4f92-a2ad-02c742f90339|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|OS|Linux x64 3.10.0-1160.76.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (64 x 999)|
|Memory (System)|125.42GB (42.72GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: nueli6047.nurnberg.cd-adapco.com|
|OS|Linux x64 3.10.0-1160.76.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (64 x 999)|
|Memory (System)|125.42GB (42.69GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
3d0df643:30602300

```

</details>

### PR DESCRIPTION
**Pull request by WardenGnaw**
This PR migrates the nativeAttach child_process calls to use 'spawn' instead of 'exec'. This allows the extension to deal with large process listing output via input/output streams instead of using a single hardcoded buffer.

Added support for canceling and timeout if the spawned process does not exit within 30 seconds.

@gregg-miskelly

Fixes: #10107

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
nit: should we change the title to something like "Fix buffer size exceeded" since the typical meaning of "BufferOverflow" is something much scarier.

File: Extension/src/Debugger/nativeAttach.ts [hunk 1]
```diff
@@ -164,30 +165,95 @@ export class PsProcessParser {
...
+                });
+            }
+
+            // Handle process exit
+            process.on('close', (code: number) => {
+                cleanUpCallbacks();
+                if (code !== 0) {
+                    reject(new Error(localize("error.processList.spawn", '"{0}" exited with code: "{1}".', command, code)));
                     return;
                 }
```
Comment (gregg-miskelly) [inline Extension/src/Debugger/nativeAttach.ts:239]: Should we check stderr first since that would be easier to understand the failure?

Comment (gregg-miskelly) [reply Extension/src/Debugger/nativeAttach.ts:239]: Or maybe include both?

**Review by gregg-miskelly — DISMISSED** [review]
Otherwise LGTM

**Review by gregg-miskelly — APPROVED** [review]

**Review by sean-mcmanus — APPROVED** [review]
